### ISSUE TITLE
SNMP v3 does'nt work with the agent 2.3.17

### ISSUE THREAD

**Issue by FRANCOIS50** [tabad/fusioninventory-agent-windows-installer#11]
I noticed that SNMP v3 with agent version 2.3.17 doesn’t work correctly.
Some files are missing, like USM.pm.  
Agent version 2.3.6 works correctly with v3 of SNMP.
see FI Forum ticket:  http://forum.fusioninventory.org/viewtopic.php?id=3088

**Comment by FRANCOIS50** [comment]
SNMP v3  doesn't work  since version 2.3.12 of the agent. Some parts of code are missing

**Comment by g-bougard** [comment]
Hi, thank you for the report.

While comparing between unix/win32 install, I'm seeing the following pm from Net::SNMP seem to be missing:
* perl/site/lib/Net/SNMP/Security/USM.pm
* perl/site/lib/Net/SNMP/Transport/IPv4/TCP.pm
* perl/site/lib/Net/SNMP/Transport/IPv6.pm
* perl/site/lib/Net/SNMP/Transport/IPv6/UDP.pm
* perl/site/lib/Net/SNMP/Transport/IPv6/TCP.pm

And as pointed in the forum thread, USM.pm depends on [Digest::SHA1](http://search.cpan.org/dist/Digest-SHA1/) module (different one than Digest::SHA), but also Crypt::DES, Digest::MD5 and Digest::HMAC.
Here Digest::SHA1 & Digest::HMAC seem to be missing from installer dependencies list.

Tabad what do you think ?

**Comment by tabad** [comment]
Thank you for the information g-bougard. I will take a look to it.

**Comment by tabad** [comment]
Please FRANCOIS50, could you try with [FIAWI 2.3.18-rc1](https://github.com/tabad/fusioninventory-agent-windows-installer/releases/tag/2.3.18-rc1)?

**Comment by tabad** [comment]
Please FRANCOIS50, could you try this time with [FIAWI 2.3.18-rc2](https://github.com/tabad/fusioninventory-agent-windows-installer/releases/tag/2.3.18-rc2)?

**Comment by tabad** [comment]
Please FRANCOIS50, could you try this time with [FIAWI 2.3.18-rc2](https://github.com/tabad/fusioninventory-agent-windows-installer/releases/tag/2.3.18-rc2)?

**Comment by FRANCOIS50** [comment]
Hi, I tested and it works now
thank you for your changes.

**Comment by tabad** [comment]
Thank you for your tests.
